package com.db4o.reflect.self;

/**
 * Contains the application-specific reflection information (that would
 * be generated by a bytecode enhancer), as opposed to the 'generic'
 * functionality contained in SelfReflector.
 */
public interface SelfReflectionRegistry {

	// TODO: this belongs to SelfReflector
	boolean isKnownClass(Class clazz);
	
	SelfField[] fieldsFor(Class clazz);
}
