package com.db4o.reflect.self;

/**
 * Contains the application-specific reflection information (that would
 * be generated by a bytecode enhancer), as opposed to the 'generic'
 * functionality contained in SelfReflector.
 */
public abstract class SelfReflectionRegistry {	

	private final static Class[] PRIMITIVES={Integer.class,Long.class,Float.class,Double.class,Short.class,Character.class,Byte.class,String.class};
	
	public boolean isPrimitive(Class clazz) {
		for (int idx = 0; idx < PRIMITIVES.length; idx++) {
			if(PRIMITIVES[idx].equals(clazz)) {
				return true;
			}
		}
		return false;
	}
	
	public abstract ClassInfo infoFor(Class clazz);
}
