output.. = bin/
source.. = src/
bin.includes = META-INF/,\
               .,\
               lib/db4o-@db4o.version.iteration.revision@-java1.2.jar,\
               lib/db4o-@db4o.version.iteration.revision@-nqopt.jar,\
               lib/db4o-@db4o.version.iteration.revision@-instrumentation.jar,\
               lib/db4o-@db4o.version.iteration.revision@-tools.jar,\
               lib/bloat-1.0.jar
